Traceback (most recent call last):
  File "E:\anaconda\envs\skip\lib\site-packages\torch\serialization.py", line 348, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "e:\anaconda\Lib\site-packages\gymnasium\envs\classic_control\policy_constraint.py", line 114, in <module>
    main(args)
  File "e:\anaconda\Lib\site-packages\gymnasium\envs\classic_control\policy_constraint.py", line 68, in main
    model.learn(int(1e3), env, train=True, critic_path=None, actor_path=None)
  File "e:\anaconda\Lib\site-packages\gymnasium\envs\classic_control\ca2c.py", line 126, in learn
    self.critic= torch.load(critic_path)
  File "E:\anaconda\envs\skip\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\anaconda\envs\skip\lib\site-packages\torch\serialization.py", line 275, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "E:\anaconda\envs\skip\lib\site-packages\torch\serialization.py", line 260, in __init__
    _check_seekable(buffer)
  File "E:\anaconda\envs\skip\lib\site-packages\torch\serialization.py", line 351, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "E:\anaconda\envs\skip\lib\site-packages\torch\serialization.py", line 344, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.